// src/utils/questionIcons.jsx
// Central icon lookup so QuestionnaireModal & TravelQuestionnaire stay in sync.
import {
  FaUmbrellaBeach,
  FaMountain,
  FaBriefcase,
  FaUsers,
  FaUser,
  FaHeart,
  FaChild,
  FaUserFriends,
  FaBalanceScale,
  FaBolt,
  FaBed,
  FaHotel,
  FaGem,
  FaHome,
  FaUtensils,
  FaThumbsUp,
  FaBan,
  FaCarrot,
  FaSun,
  FaCloudSun,
  FaSnowflake,
  FaGlobe,
  FaWalking,
  FaBus,
  FaCar,
  FaUserTie,
  FaWallet,
  FaMoneyBillWave,
  FaCreditCard,
  FaCrown,
  FaTree,
  FaLandmark,
  FaMoon,
  FaShoppingBag,
  FaCalendarAlt,
  FaClock,
  FaBolt as FaLastMinute,
  FaQuestion,
} from "react-icons/fa";

export const QUESTION_ICONS = {
  relaxation: FaUmbrellaBeach,
  adventure: FaMountain,
  business: FaBriefcase,
  family: FaUsers,
  solo: FaUser,
  partner: FaHeart,
  friends: FaUserFriends,
  balanced: FaBalanceScale,
  spontaneous: FaBolt,
  hostel: FaBed,
  hotel: FaHotel,
  luxury: FaGem,
  local: FaHome,
  food: FaUtensils,
  nice: FaThumbsUp,
  notimportant: FaBan,
  dietary: FaCarrot,
  sunny: FaSun,
  mild: FaCloudSun,
  snowy: FaSnowflake,
  any: FaGlobe,
  walking: FaWalking,
  transport: FaBus,
  car: FaCar,
  driver: FaUserTie,
  budget: FaWallet,
  midbudget: FaMoneyBillWave,
  highbudget: FaCreditCard,
  nature: FaTree,
  history: FaLandmark,
  nightlife: FaMoon,
  shopping: FaShoppingBag,
  planahead: FaCalendarAlt,
  weeks: FaClock,
  lastminute: FaLastMinute,
  deciding: FaQuestion,
};

export const getQuestionIcon = (key) => QUESTION_ICONS[key] || FaQuestion;
